//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConvenienceStore.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ConvenienceStoreEntities : DbContext
    {
        public ConvenienceStoreEntities()
            : base("name=ConvenienceStoreEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CaLam> CaLams { get; set; }
        public virtual DbSet<ChiNhanh> ChiNhanhs { get; set; }
        public virtual DbSet<HoaDon> HoaDons { get; set; }
        public virtual DbSet<HoaDonSanPham> HoaDonSanPhams { get; set; }
        public virtual DbSet<KeToan> KeToans { get; set; }
        public virtual DbSet<LoaiHang> LoaiHangs { get; set; }
        public virtual DbSet<MatHang> MatHangs { get; set; }
        public virtual DbSet<MatHangChiNhanh> MatHangChiNhanhs { get; set; }
        public virtual DbSet<Nguoi> Nguois { get; set; }
        public virtual DbSet<NhaCungCap> NhaCungCaps { get; set; }
        public virtual DbSet<NhanVienBanHang> NhanVienBanHangs { get; set; }
        public virtual DbSet<NhanVienBanHangCaLam> NhanVienBanHangCaLams { get; set; }
        public virtual DbSet<NhanVienThuKho> NhanVienThuKhoes { get; set; }
        public virtual DbSet<NhanVienThuKhoMatHang> NhanVienThuKhoMatHangs { get; set; }
        public virtual DbSet<QuanLy> QuanLies { get; set; }
    }
}
