//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConvenienceStore.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVienBanHangCaLam
    {
        public string maNVBH { get; set; }
        public string maCa { get; set; }
        public System.DateTime ngayLam { get; set; }
    
        public virtual CaLam CaLam { get; set; }
        public virtual NhanVienBanHang NhanVienBanHang { get; set; }
    }
}
