//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Services.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ConvenienceStoreEntities : DbContext
    {
        public ConvenienceStoreEntities()
            : base("name=ConvenienceStoreEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CaLam> CaLam { get; set; }
        public virtual DbSet<ChiNhanh> ChiNhanh { get; set; }
        public virtual DbSet<HoaDon> HoaDon { get; set; }
        public virtual DbSet<HoaDonSanPham> HoaDonSanPham { get; set; }
        public virtual DbSet<KeToan> KeToan { get; set; }
        public virtual DbSet<LoaiHang> LoaiHang { get; set; }
        public virtual DbSet<MatHang> MatHang { get; set; }
        public virtual DbSet<MatHangChiNhanh> MatHangChiNhanh { get; set; }
        public virtual DbSet<Nguoi> Nguoi { get; set; }
        public virtual DbSet<NhaCungCap> NhaCungCap { get; set; }
        public virtual DbSet<NhanVienBanHang> NhanVienBanHang { get; set; }
        public virtual DbSet<NhanVienBanHangCaLam> NhanVienBanHangCaLam { get; set; }
        public virtual DbSet<NhanVienThuKho> NhanVienThuKho { get; set; }
        public virtual DbSet<NhanVienThuKhoMatHang> NhanVienThuKhoMatHang { get; set; }
        public virtual DbSet<QuanLy> QuanLy { get; set; }
    }
}
