//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Services.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nguoi
    {
        public string userID { get; set; }
        public string passwd { get; set; }
        public string hoTen { get; set; }
        public Nullable<System.DateTime> ngaySinh { get; set; }
        public Nullable<bool> gioiTinh { get; set; }
        public string cmnd { get; set; }
        public string sdt { get; set; }
        public string email { get; set; }
        public string diaChi { get; set; }
    
        public virtual KeToan KeToan { get; set; }
        public virtual NhanVienBanHang NhanVienBanHang { get; set; }
        public virtual NhanVienThuKho NhanVienThuKho { get; set; }
        public virtual QuanLy QuanLy { get; set; }
    }
}
